variables:
  repositoryServer: 'jannemattila/ua-home-assistant-server'

trigger:
- main
- develop

name: 1.0.$(Rev:r)
stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHub'
        repository: $(repositoryServer)
        command: 'buildAndPush'
        Dockerfile: 'src/UA-home-assistant-server/Dockerfile'
        tags: |
          $(Build.BuildNumber)
          latest
